name: Deploy Worker

on:
  repository_dispatch:
    types: [deploy-worker]

jobs:
  deploy:
    name: Deploy Worker to Render
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        uses: johnnymanz/github-render-deploy@v1.0.0
        with:
          service-id: ${{ secrets.RENDER_WORKER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
