name: Deploy Worker

on:
  workflow_call:
  repository_dispatch:
    types: [deploy-worker]

jobs:
  deploy:
    name: Deploy Worker to Render
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_WORKER_DEPLOY_HOOK }}