name: Deploy API

on:
  workflow_call:
  repository_dispatch:
    types: [deploy-api]

jobs:
  deploy:
    name: Deploy API to Render
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_API_DEPLOY_HOOK }}